services:
  mongodb:
    build: 
      context: ./docker/mongodb
    container_name: restaurantos-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: restaurantos-admin
      MONGO_INITDB_ROOT_PASSWORD: restaurantos-password

    command: [
      "mongod", 
      "--replSet", 
      "rs0", 
      "--bind_ip_all", 
      "--keyFile",
      "/etc/mongo-keyfile"
    ]

    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: